### ISSUE TITLE
Unable to use on >2.1.0 because of forms api

### ISSUE THREAD

**Issue by Wouter0100** [hypeJunction/Elgg-groups_invite#1]
Due the requirement to have the forms_api plugin enabled, I'm unable to use this plugin on Elgg 2.1.0 and up. This because the forms_api isn't able to being installed on this Elgg version (https://github.com/hypeJunction/Elgg-forms_api/blob/master/manifest.xml#L16-L20).

**Comment by hypeJunction** [comment]
Yeah, haven't gotten to it. 
For now, add this to your theme's manifest:

``` xml
<provides>
   <type>plugin</type>
   <name>forms_api</name>
</profiles>
```

**Comment by Wouter0100** [comment]
Unfortunately, the base theme used is `aalborg_theme`, which I'm, ofcourse, unable to edit. All changes made to the theme specific for this project is in the app itself (e.g. a `views` dir in the root dir) which doesn't have a manifest, and as far as I know, doesn't support it cuz it isn't a plugin.

**Comment by hypeJunction** [comment]
Just create a new dummy plugin.
