### ISSUE TITLE
error elgg_tokeninput  while doing composer install  inside this plugin

### ISSUE THREAD

**Issue by dipenpatel235** [hypeJunction/Elgg-groups_invite#2]
[root@localost groups_invite]# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hypejunction/elgg_tokeninput 4.1.3 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - hypejunction/elgg_tokeninput 4.1.2 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - hypejunction/elgg_tokeninput 4.1.1 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - hypejunction/elgg_tokeninput 4.1.0 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - hypejunction/elgg_tokeninput 4.0.2 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - hypejunction/elgg_tokeninput 4.0.1 requires bower-asset/jquery-tokeninput ~1.7.0 -> no matching package found.
    - Installation request for hypejunction/elgg_tokeninput ~4.0 -> satisfiable by hypejunction/elgg_tokeninput[4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by hypeJunction** [comment]
Install composer asset plugin globally. Check Elgg install docs for details.

**Comment by dipenpatel235** [comment]
ok..thanks
